name: Deploy Production 🚀

on:
  release:
    types:
      - published
      - edited

jobs:
  deploy-production:
    name: Deploy to production server 🚀
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy to production server
        uses: appleboy/ssh-action@v1.0.3
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          APP_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/pacmusic
          APP_TAG: ${{ github.event.release.tag_name }}
          APP_PROD_PATH: ${{ vars.APP_PROD_PATH }}
          GIT_URL: ${{ secrets.GIT_URL }}
          APP_PROD_PORT: ${{ secrets.APP_PROD_PORT }}
          MINIO_PROD_ENDPOINT: ${{ secrets.MINIO_PROD_ENDPOINT }}
          MINIO_PROD_ACCESS_KEY: ${{ secrets.MINIO_PROD_ACCESS_KEY }}
          MINIO_PROD_SECRET_KEY: ${{ secrets.MINIO_PROD_SECRET_KEY }}

        with:
          host: ${{ secrets.SSH_HOST_PRODUCTION }}
          username: ${{ secrets.SSH_USER_NAME_PRODUCTION }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PRODUCTION }}
          envs: DOCKERHUB_USERNAME, DOCKERHUB_TOKEN, APP_IMAGE, APP_TAG, APP_PROD_PATH, GIT_URL, APP_PROD_PORT, MINIO_PROD_ENDPOINT, MINIO_PROD_ACCESS_KEY, MINIO_PROD_SECRET_KEY
          script: |

            sudo docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN

            if [[ -d "${APP_PROD_PATH}" ]]; then 
              cd $APP_PROD_PATH
              sudo docker compose down
              git pull origin main
            else
              ssh-keyscan github.com > ~/.ssh/known_hosts
              git clone $GIT_URL $APP_PROD_PATH
              cd $APP_PROD_PATH
            fi

            # If there are any envars update
            echo "APP_PROD_PORT=${{ secrets.APP_PROD_PORT }}" > .env
            echo "MINIO_PROD_ENDPOINT=${{ secrets.MINIO_PROD_ENDPOINT }}" >> .env
            echo "MINIO_PROD_ACCESS_KEY=${{ secrets.MINIO_PROD_ACCESS_KEY }}" >> .env
            echo "MINIO_PROD_SECRET_KEY=${{ secrets.MINIO_PROD_SECRET_KEY }}" >> .env
            echo "APP_IMAGE=${{ secrets.DOCKERHUB_USERNAME }}/pacmusic" >> .env
            echo "APP_TAG=$APP_TAG" >> .env
            
            # Run app
            sudo docker compose up --build --detach pacmusic-prod

      - name: Hit Endpoint
        run: |
          sleep 20
          sudo docker ps -a
          curl ${{ secrets.PROD_URL }}